-- =============================================================================
-- Farm Express — Migration 0001: initial schema, functions/triggers, RLS
-- =============================================================================
-- Generated by concatenating schema.sql + functions.sql + policies.sql.
-- Those three files are the reviewable source; this file is the frozen,
-- applied snapshot — never edit a migration after it has run anywhere.
-- Future schema changes land as a new 0002_*.sql migration, with
-- schema.sql/functions.sql/policies.sql updated to match.
-- =============================================================================

-- =============================================================================
-- Farm Express — Database Schema (Step 4)
-- =============================================================================
-- Target: Supabase Postgres. Run via `supabase db push` (see
-- database/migrations/0001_init.sql, which is the actual applied migration —
-- this file plus functions.sql and policies.sql are the organized, reviewable
-- source that migration mirrors).
--
-- Design notes:
--   * Multi-tenant by `farm_id` on every farm-scoped table. Row Level
--     Security (policies.sql) enforces the tenant boundary — the app never
--     has to remember to add `WHERE farm_id = ...` for security purposes,
--     only for query correctness.
--   * `public.users` is a 1:1 profile row keyed by `auth.users.id`
--     (Supabase's own auth table), created automatically by a trigger
--     (see functions.sql#handle_new_user) the moment someone verifies their
--     first OTP. It starts with `farm_id = NULL`; the `complete_owner_profile`
--     RPC fills that in once the user names their farm (see app's Step 3
--     "complete profile" screen).
--   * `workers.user_id` is an optional link to `public.users` — set only
--     when a permanent worker is invited to log in as "labour" (Step 13's
--     team-invite flow). Until then, worker records exist purely as data
--     entered by the owner/supervisor with no login of their own.
--   * "salary" as a concept spans three things rather than one table:
--     `workers.monthly_salary` (the fixed figure the owner sets once),
--     `salary_advances` (running ledger), and `salary_payments` (the
--     computed, generated slip for a period). Keeping them separate avoids
--     redundant/denormalized copies of the same number.
-- =============================================================================

create extension if not exists "pgcrypto"; -- gen_random_uuid()

-- =============================================================================
-- roles — reference table (kept normalized/extensible rather than a bare
-- Postgres enum, so labels can change without a migration).
-- =============================================================================
create table if not exists public.roles (
  id text primary key,
  label text not null
);

insert into public.roles (id, label) values
  ('owner', 'Farm Owner'),
  ('supervisor', 'Farm Supervisor'),
  ('labour', 'Labour')
on conflict (id) do nothing;

-- =============================================================================
-- farms
-- =============================================================================
create table if not exists public.farms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid not null references auth.users (id) on delete cascade,
  location text,
  phone text,
  currency text not null default 'INR',
  language text not null default 'en',
  created_at timestamptz not null default now()
);

create index if not exists idx_farms_owner on public.farms (owner_id);

-- =============================================================================
-- users — 1:1 profile for every authenticated person (owner/supervisor/labour)
-- =============================================================================
create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  farm_id uuid references public.farms (id) on delete set null,
  full_name text not null default '',
  role text not null default 'owner' references public.roles (id),
  email text,
  phone text,
  avatar_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_users_farm on public.users (farm_id);

-- =============================================================================
-- workers — permanent + casual labour
-- =============================================================================
create table if not exists public.workers (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  user_id uuid references public.users (id) on delete set null,
  type text not null check (type in ('permanent', 'casual')),
  name text not null,
  photo_url text,
  phone text,
  address text,
  village text,
  joining_date date,
  monthly_salary numeric(12, 2) check (monthly_salary is null or monthly_salary >= 0),
  daily_wage numeric(12, 2) check (daily_wage is null or daily_wage >= 0),
  bank_details jsonb,
  status text not null default 'active' check (status in ('active', 'inactive')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_workers_farm on public.workers (farm_id);
create index if not exists idx_workers_type on public.workers (farm_id, type);
create index if not exists idx_workers_status on public.workers (farm_id, status);
create unique index if not exists idx_workers_user on public.workers (user_id) where user_id is not null;

-- =============================================================================
-- attendance — one row per worker per day
-- =============================================================================
create table if not exists public.attendance (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  worker_id uuid not null references public.workers (id) on delete cascade,
  date date not null,
  status text not null check (status in ('present', 'absent', 'half_day', 'leave', 'late')),
  todays_wage numeric(12, 2) check (todays_wage is null or todays_wage >= 0),
  work_done text,
  remarks text,
  marked_by uuid not null references public.users (id),
  created_at timestamptz not null default now(),
  unique (worker_id, date)
);

create index if not exists idx_attendance_farm_date on public.attendance (farm_id, date);
create index if not exists idx_attendance_worker on public.attendance (worker_id, date);

-- =============================================================================
-- salary_advances — running ledger per worker
-- =============================================================================
create table if not exists public.salary_advances (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  worker_id uuid not null references public.workers (id) on delete cascade,
  date date not null default current_date,
  amount numeric(12, 2) not null check (amount > 0),
  reason text,
  remaining_balance numeric(12, 2) not null check (remaining_balance >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_advances_worker on public.salary_advances (worker_id, date);
create index if not exists idx_advances_farm on public.salary_advances (farm_id);

-- =============================================================================
-- salary_payments — generated monthly slip (permanent) / period rollup (casual)
-- =============================================================================
create table if not exists public.salary_payments (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  worker_id uuid not null references public.workers (id) on delete cascade,
  period_start date not null,
  period_end date not null,
  working_days numeric(5, 1) not null default 0,
  leaves numeric(5, 1) not null default 0,
  half_days numeric(5, 1) not null default 0,
  advance_deducted numeric(12, 2) not null default 0 check (advance_deducted >= 0),
  bonuses numeric(12, 2) not null default 0 check (bonuses >= 0),
  deductions numeric(12, 2) not null default 0 check (deductions >= 0),
  gross_amount numeric(12, 2) not null check (gross_amount >= 0),
  net_amount numeric(12, 2) not null check (net_amount >= 0),
  status text not null default 'pending' check (status in ('pending', 'paid')),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  check (period_end >= period_start),
  unique (worker_id, period_start, period_end)
);

create index if not exists idx_salary_payments_farm_period on public.salary_payments (farm_id, period_start);
create index if not exists idx_salary_payments_status on public.salary_payments (farm_id, status);

-- =============================================================================
-- stock — current inventory (one row per item)
-- =============================================================================
create table if not exists public.stock (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  category text not null check (
    category in ('coconut_bags', 'arecanut_bags', 'pepper', 'banana', 'coffee', 'mango', 'custom')
  ),
  name text not null,
  unit text not null,
  quantity numeric(12, 2) not null default 0 check (quantity >= 0),
  location text,
  low_stock_threshold numeric(12, 2) check (low_stock_threshold is null or low_stock_threshold >= 0),
  added_by uuid not null references public.users (id),
  updated_by uuid not null references public.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_stock_farm on public.stock (farm_id);
create unique index if not exists idx_stock_farm_name on public.stock (farm_id, name);

-- =============================================================================
-- stock_history — append-only daily ledger. Never updated or deleted by the
-- app (see policies.sql — no UPDATE/DELETE policy exists for this table).
-- =============================================================================
create table if not exists public.stock_history (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  stock_item_id uuid not null references public.stock (id) on delete cascade,
  date date not null default current_date,
  opening_quantity numeric(12, 2) not null default 0,
  harvested_today numeric(12, 2) not null default 0 check (harvested_today >= 0),
  sold_today numeric(12, 2) not null default 0 check (sold_today >= 0),
  damaged numeric(12, 2) not null default 0 check (damaged >= 0),
  remaining_stock numeric(12, 2) not null default 0 check (remaining_stock >= 0),
  notes text,
  recorded_by uuid not null references public.users (id),
  created_at timestamptz not null default now(),
  unique (stock_item_id, date)
);

create index if not exists idx_stock_history_item_date on public.stock_history (stock_item_id, date);
create index if not exists idx_stock_history_farm_date on public.stock_history (farm_id, date);

-- =============================================================================
-- buyers
-- =============================================================================
create table if not exists public.buyers (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  name text not null,
  phone text,
  address text,
  created_at timestamptz not null default now()
);

create index if not exists idx_buyers_farm on public.buyers (farm_id);

-- =============================================================================
-- sales
-- =============================================================================
create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  stock_item_id uuid not null references public.stock (id),
  buyer_id uuid not null references public.buyers (id),
  quantity numeric(12, 2) not null check (quantity > 0),
  rate numeric(12, 2) not null check (rate >= 0),
  amount numeric(12, 2) not null check (amount >= 0),
  transport_cost numeric(12, 2) not null default 0 check (transport_cost >= 0),
  commission numeric(12, 2) not null default 0 check (commission >= 0),
  net_amount numeric(12, 2) not null check (net_amount >= 0),
  payment_method text not null check (payment_method in ('cash', 'upi', 'bank', 'credit')),
  date date not null default current_date,
  remarks text,
  recorded_by uuid not null references public.users (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_sales_farm_date on public.sales (farm_id, date);
create index if not exists idx_sales_buyer on public.sales (buyer_id);

-- =============================================================================
-- expenses
-- =============================================================================
create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  category text not null check (
    category in (
      'fertilizer', 'fuel', 'pesticides', 'seeds', 'electricity',
      'water', 'maintenance', 'machine_repair', 'transport', 'miscellaneous'
    )
  ),
  amount numeric(12, 2) not null check (amount > 0),
  date date not null default current_date,
  bill_image_url text,
  notes text,
  recorded_by uuid not null references public.users (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_expenses_farm_date on public.expenses (farm_id, date);
create index if not exists idx_expenses_category on public.expenses (farm_id, category);

-- =============================================================================
-- notifications
-- =============================================================================
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  user_id uuid references public.users (id) on delete cascade,
  title text not null,
  body text not null,
  type text not null check (
    type in ('attendance', 'stock', 'salary', 'payment', 'low_stock', 'general')
  ),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user on public.notifications (user_id, is_read);
create index if not exists idx_notifications_farm on public.notifications (farm_id, created_at desc);

-- =============================================================================
-- settings — one row per farm
-- =============================================================================
create table if not exists public.settings (
  farm_id uuid primary key references public.farms (id) on delete cascade,
  notifications_enabled boolean not null default true,
  low_stock_alerts_enabled boolean not null default true,
  attendance_reminder_time time not null default '19:00',
  theme text not null default 'system' check (theme in ('light', 'dark', 'system')),
  updated_at timestamptz not null default now()
);

-- =============================================================================
-- activity_logs — audit trail, append-only (see policies.sql)
-- =============================================================================
create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms (id) on delete cascade,
  user_id uuid not null references public.users (id),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_logs_farm on public.activity_logs (farm_id, created_at desc);
create index if not exists idx_activity_logs_entity on public.activity_logs (entity_type, entity_id);

-- =============================================================================
-- Farm Express — Functions & Triggers (Step 4)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- current_farm_id() / current_role()
-- -----------------------------------------------------------------------------
-- Read the requesting user's farm/role once, from `public.users`, for reuse
-- across every RLS policy in policies.sql. SECURITY DEFINER + a fixed
-- search_path avoids the classic "RLS policy queries a table that itself has
-- RLS enabled" recursion trap (the function runs as its owner, bypassing the
-- caller's RLS on `public.users`, then the *caller's* RLS on every other
-- table still applies normally using the value it returns).
-- -----------------------------------------------------------------------------
create or replace function public.current_farm_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select farm_id from public.users where id = auth.uid();
$$;

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.users where id = auth.uid();
$$;

-- -----------------------------------------------------------------------------
-- set_updated_at() — generic trigger to keep `updated_at` honest
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_workers_updated_at on public.workers;
create trigger trg_workers_updated_at
  before update on public.workers
  for each row execute function public.set_updated_at();

drop trigger if exists trg_stock_updated_at on public.stock;
create trigger trg_stock_updated_at
  before update on public.stock
  for each row execute function public.set_updated_at();

drop trigger if exists trg_settings_updated_at on public.settings;
create trigger trg_settings_updated_at
  before update on public.settings
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- handle_new_user() — runs the instant someone verifies their first OTP /
-- completes Google sign-in. Creates a bare profile row (role defaults to
-- 'owner', farm_id NULL) — `complete_owner_profile` below fills in the farm.
-- -----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, full_name, email, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'fullName', ''),
    new.email,
    new.phone
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_on_auth_user_created on auth.users;
create trigger trg_on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- complete_owner_profile(...) — called once, right after a brand-new user's
-- first sign-in (see app/(auth)/complete-profile.tsx). Creates the farm and
-- links the caller's own profile row to it. SECURITY DEFINER because the
-- caller doesn't have (and shouldn't need) a direct INSERT policy on
-- `farms` — this RPC is the only sanctioned way a farm gets created.
-- -----------------------------------------------------------------------------
create or replace function public.complete_owner_profile(p_full_name text, p_farm_name text)
returns public.users
language plpgsql
security definer
set search_path = public
as $$
declare
  v_farm_id uuid;
  v_result public.users;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if length(trim(p_full_name)) = 0 or length(trim(p_farm_name)) = 0 then
    raise exception 'Full name and farm name are required';
  end if;

  insert into public.farms (name, owner_id)
  values (trim(p_farm_name), auth.uid())
  returning id into v_farm_id;

  insert into public.settings (farm_id) values (v_farm_id)
  on conflict (farm_id) do nothing;

  update public.users
  set full_name = trim(p_full_name),
      farm_id = v_farm_id,
      role = 'owner'
  where id = auth.uid()
  returning * into v_result;

  return v_result;
end;
$$;

grant execute on function public.complete_owner_profile(text, text) to authenticated;

-- =============================================================================
-- Farm Express — Row Level Security (Step 4)
-- =============================================================================
-- Every farm-scoped table: readable by anyone belonging to that farm,
-- writable by owner/supervisor (per constants/config.ts's PERMISSIONS
-- matrix), deletable by owner only. `stock_history` and `activity_logs` are
-- append-only — intentionally no UPDATE/DELETE policy exists for them, so
-- even the owner can only INSERT/SELECT, matching "history should never be
-- deleted".
--
-- `current_farm_id()` / `current_role()` (functions.sql) read the caller's
-- own profile row once per statement; keeping that logic in one place means
-- a future role (e.g. "accountant") is a one-function change, not a
-- 15-policy rewrite.
-- =============================================================================

alter table public.roles enable row level security;
alter table public.farms enable row level security;
alter table public.users enable row level security;
alter table public.workers enable row level security;
alter table public.attendance enable row level security;
alter table public.salary_advances enable row level security;
alter table public.salary_payments enable row level security;
alter table public.stock enable row level security;
alter table public.stock_history enable row level security;
alter table public.buyers enable row level security;
alter table public.sales enable row level security;
alter table public.expenses enable row level security;
alter table public.notifications enable row level security;
alter table public.settings enable row level security;
alter table public.activity_logs enable row level security;

-- -----------------------------------------------------------------------------
-- roles — public reference data, read-only to every signed-in user
-- -----------------------------------------------------------------------------
drop policy if exists "roles_select_authenticated" on public.roles;
create policy "roles_select_authenticated" on public.roles
  for select to authenticated using (true);

-- -----------------------------------------------------------------------------
-- farms
-- -----------------------------------------------------------------------------
drop policy if exists "farms_select_own" on public.farms;
create policy "farms_select_own" on public.farms
  for select to authenticated
  using (id = public.current_farm_id() or owner_id = auth.uid());

drop policy if exists "farms_update_owner" on public.farms;
create policy "farms_update_owner" on public.farms
  for update to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

-- No INSERT policy: farms are only created via the `complete_owner_profile`
-- SECURITY DEFINER RPC, which bypasses RLS by design.

-- -----------------------------------------------------------------------------
-- users — everyone can see their own row + co-workers on the same farm;
-- only the owner can change someone else's role.
-- -----------------------------------------------------------------------------
drop policy if exists "users_select_self_or_farm" on public.users;
create policy "users_select_self_or_farm" on public.users
  for select to authenticated
  using (id = auth.uid() or farm_id = public.current_farm_id());

drop policy if exists "users_update_self" on public.users;
create policy "users_update_self" on public.users
  for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists "users_update_by_owner" on public.users;
create policy "users_update_by_owner" on public.users
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner')
  with check (farm_id = public.current_farm_id());

-- -----------------------------------------------------------------------------
-- workers
-- -----------------------------------------------------------------------------
drop policy if exists "workers_select" on public.workers;
create policy "workers_select" on public.workers
  for select to authenticated using (farm_id = public.current_farm_id());

drop policy if exists "workers_write" on public.workers;
create policy "workers_write" on public.workers
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "workers_update" on public.workers;
create policy "workers_update" on public.workers
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "workers_delete" on public.workers;
create policy "workers_delete" on public.workers
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

-- -----------------------------------------------------------------------------
-- attendance — labour can only ever see rows for their own linked worker
-- -----------------------------------------------------------------------------
drop policy if exists "attendance_select" on public.attendance;
create policy "attendance_select" on public.attendance
  for select to authenticated
  using (
    farm_id = public.current_farm_id()
    and (
      public.current_role() in ('owner', 'supervisor')
      or worker_id in (select id from public.workers where user_id = auth.uid())
    )
  );

drop policy if exists "attendance_write" on public.attendance;
create policy "attendance_write" on public.attendance
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "attendance_update" on public.attendance;
create policy "attendance_update" on public.attendance
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "attendance_delete" on public.attendance;
create policy "attendance_delete" on public.attendance
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

-- -----------------------------------------------------------------------------
-- salary_advances / salary_payments — same "labour sees only their own" rule
-- -----------------------------------------------------------------------------
drop policy if exists "advances_select" on public.salary_advances;
create policy "advances_select" on public.salary_advances
  for select to authenticated
  using (
    farm_id = public.current_farm_id()
    and (
      public.current_role() in ('owner', 'supervisor')
      or worker_id in (select id from public.workers where user_id = auth.uid())
    )
  );

drop policy if exists "advances_write" on public.salary_advances;
create policy "advances_write" on public.salary_advances
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "advances_update" on public.salary_advances;
create policy "advances_update" on public.salary_advances
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "advances_delete" on public.salary_advances;
create policy "advances_delete" on public.salary_advances
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

drop policy if exists "salary_payments_select" on public.salary_payments;
create policy "salary_payments_select" on public.salary_payments
  for select to authenticated
  using (
    farm_id = public.current_farm_id()
    and (
      public.current_role() in ('owner', 'supervisor')
      or worker_id in (select id from public.workers where user_id = auth.uid())
    )
  );

drop policy if exists "salary_payments_write" on public.salary_payments;
create policy "salary_payments_write" on public.salary_payments
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "salary_payments_update" on public.salary_payments;
create policy "salary_payments_update" on public.salary_payments
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "salary_payments_delete" on public.salary_payments;
create policy "salary_payments_delete" on public.salary_payments
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

-- -----------------------------------------------------------------------------
-- stock (current inventory)
-- -----------------------------------------------------------------------------
drop policy if exists "stock_select" on public.stock;
create policy "stock_select" on public.stock
  for select to authenticated using (farm_id = public.current_farm_id());

drop policy if exists "stock_write" on public.stock;
create policy "stock_write" on public.stock
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "stock_update" on public.stock;
create policy "stock_update" on public.stock
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "stock_delete" on public.stock;
create policy "stock_delete" on public.stock
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

-- -----------------------------------------------------------------------------
-- stock_history — append-only: SELECT + INSERT only, no UPDATE, no DELETE,
-- for anyone, including the owner. This is deliberate (see schema.sql).
-- -----------------------------------------------------------------------------
drop policy if exists "stock_history_select" on public.stock_history;
create policy "stock_history_select" on public.stock_history
  for select to authenticated using (farm_id = public.current_farm_id());

drop policy if exists "stock_history_insert" on public.stock_history;
create policy "stock_history_insert" on public.stock_history
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

-- -----------------------------------------------------------------------------
-- buyers
-- -----------------------------------------------------------------------------
drop policy if exists "buyers_select" on public.buyers;
create policy "buyers_select" on public.buyers
  for select to authenticated using (farm_id = public.current_farm_id());

drop policy if exists "buyers_write" on public.buyers;
create policy "buyers_write" on public.buyers
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "buyers_update" on public.buyers;
create policy "buyers_update" on public.buyers
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "buyers_delete" on public.buyers;
create policy "buyers_delete" on public.buyers
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

-- -----------------------------------------------------------------------------
-- sales
-- -----------------------------------------------------------------------------
drop policy if exists "sales_select" on public.sales;
create policy "sales_select" on public.sales
  for select to authenticated using (farm_id = public.current_farm_id());

drop policy if exists "sales_write" on public.sales;
create policy "sales_write" on public.sales
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "sales_update" on public.sales;
create policy "sales_update" on public.sales
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "sales_delete" on public.sales;
create policy "sales_delete" on public.sales
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

-- -----------------------------------------------------------------------------
-- expenses
-- -----------------------------------------------------------------------------
drop policy if exists "expenses_select" on public.expenses;
create policy "expenses_select" on public.expenses
  for select to authenticated using (farm_id = public.current_farm_id());

drop policy if exists "expenses_write" on public.expenses;
create policy "expenses_write" on public.expenses
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "expenses_update" on public.expenses;
create policy "expenses_update" on public.expenses
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'))
  with check (farm_id = public.current_farm_id());

drop policy if exists "expenses_delete" on public.expenses;
create policy "expenses_delete" on public.expenses
  for delete to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner');

-- -----------------------------------------------------------------------------
-- notifications — each user only sees their own (or farm-wide broadcasts
-- where user_id is null); anyone farm-scoped can be the writer (the app
-- server-side/background job role, or an owner/supervisor action).
-- -----------------------------------------------------------------------------
drop policy if exists "notifications_select" on public.notifications;
create policy "notifications_select" on public.notifications
  for select to authenticated
  using (farm_id = public.current_farm_id() and (user_id = auth.uid() or user_id is null));

drop policy if exists "notifications_insert" on public.notifications;
create policy "notifications_insert" on public.notifications
  for insert to authenticated
  with check (farm_id = public.current_farm_id());

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own" on public.notifications
  for update to authenticated
  using (farm_id = public.current_farm_id() and user_id = auth.uid())
  with check (farm_id = public.current_farm_id());

-- -----------------------------------------------------------------------------
-- settings — owner only
-- -----------------------------------------------------------------------------
drop policy if exists "settings_select" on public.settings;
create policy "settings_select" on public.settings
  for select to authenticated using (farm_id = public.current_farm_id());

drop policy if exists "settings_update" on public.settings;
create policy "settings_update" on public.settings
  for update to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() = 'owner')
  with check (farm_id = public.current_farm_id());

-- -----------------------------------------------------------------------------
-- activity_logs — append-only audit trail: SELECT + INSERT only
-- -----------------------------------------------------------------------------
drop policy if exists "activity_logs_select" on public.activity_logs;
create policy "activity_logs_select" on public.activity_logs
  for select to authenticated
  using (farm_id = public.current_farm_id() and public.current_role() in ('owner', 'supervisor'));

drop policy if exists "activity_logs_insert" on public.activity_logs;
create policy "activity_logs_insert" on public.activity_logs
  for insert to authenticated
  with check (farm_id = public.current_farm_id() and user_id = auth.uid());
